<?php
/**
 * Language labels for database tables/fields belonging to extension "wse_events"
 *
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'tx_wseevents_events' => 'WSE Events',	
		'tx_wseevents_events.name' => 'Event name',	
		'tx_wseevents_events.location' => 'Location',	
		'tx_wseevents_locations' => 'WSE Locations',	
		'tx_wseevents_locations.name' => 'Name of Location',	
		'tx_wseevents_rooms' => 'WSE Rooms',	
		'tx_wseevents_rooms.name' => 'Room name',	
		'tx_wseevents_rooms.seats' => 'Number of seats',	
		'tx_wseevents_rooms.location' => 'Location',	
		'tx_wseevents_timeslots' => 'WSE Timeslots',	
		'tx_wseevents_timeslots.event' => 'Name of Event',	
		'tx_wseevents_timeslots.name' => 'Name of timeslot',	
		'tx_wseevents_timeslots.begin' => 'Begin of session',	
		'tx_wseevents_timeslots.end' => 'End of session',
		'tx_wseevents_timeslots.sessions' => 'Name of session',
		'tx_wseevents_timeslots.nosessions' => '- no session planned -',
		'tx_wseevents_sessions' => 'WSE Sessions',	
		'tx_wseevents_sessions.event' => 'Event',	
		'tx_wseevents_sessions.name' => 'Session name',	
		'tx_wseevents_sessions.speaker' => 'Speaker',	
		'tx_wseevents_sessions.room' => 'Room',	
		'tx_wseevents_sessions.timeslots' => 'Time slots',	
		'tx_wseevents_sessions.categorie' => 'Categorie',	
		'tx_wseevents_sessions.number' => 'Session number',	
		'tx_wseevents_sessions.teaser' => 'Teaser text',	
		'tx_wseevents_sessions.description' => 'Session Description',	
		'tx_wseevents_speakers' => 'WSE Speakers',	
		'tx_wseevents_speakers.name' => 'Name',	
		'tx_wseevents_speakers.email' => 'E-Mail address',	
		'tx_wseevents_categories' => 'WSE Categories',	
		'tx_wseevents_categories.name' => 'Name of categorie',	
		'tx_wseevents_categories.shortkey' => 'Short key',	
		'tt_content.list_type_pi1' => 'WSE Events Flexform Plugin',
	   'tt_content.pi_flexform.sheet_general' => 'General Settings',
	   'tt_content.pi_flexform.sheet_display' => 'Display Settings',
	   'tt_content.pi_flexform.sheet_error' => 'Error Handling Settings',
	   'tt_content.pi_flexform.disable_rte' => 'Disable the Rich Text Editor',
	   'tt_content.pi_flexform.show_errors' => 'Show Errors',
	   'tt_content.pi_flexform.prepend_text' => 'Text to prepend errors with',
		'wseevents.pi_flexform.dynListType' => 'Viewmode',
		'wseevents.pi_flexform.eventStorage' => 'Event storage',
		'wseevents.pi_flexform.singleSession' => 'Session single view page',
	),
	'de' => Array (
		'tx_wseevents_events' => 'WSE Veranstaltungen',	
		'tx_wseevents_events.name' => 'Veranstaltungsname',	
		'tx_wseevents_events.location' => 'Veranstaltungsort',	
		'tx_wseevents_locations' => 'WSE Veranstaltungsorte',	
		'tx_wseevents_locations.name' => 'Name des Veranstaltungsortes',	
		'tx_wseevents_rooms' => 'WSE Räume',	
		'tx_wseevents_rooms.name' => 'Raumname',	
		'tx_wseevents_rooms.seats' => 'Anzahl Plätze',	
		'tx_wseevents_rooms.location' => 'Veranstaltungsort',	
		'tx_wseevents_timeslots' => 'WSE Vortragszeiten',	
		'tx_wseevents_timeslots.event' => 'Veranstaltung',	
		'tx_wseevents_timeslots.name' => 'Name der Vortragszeit',	
		'tx_wseevents_timeslots.begin' => 'Beginn des Vortrags',	
		'tx_wseevents_timeslots.end' => 'Ende des Vortrags',	
		'tx_wseevents_sessions' => 'WSE Vorträge',	
		'tx_wseevents_sessions.event' => 'Veranstaltung',	
		'tx_wseevents_sessions.name' => 'Vortragsname',	
		'tx_wseevents_sessions.speaker' => 'Sprecher',	
		'tx_wseevents_sessions.room' => 'Raum',	
		'tx_wseevents_sessions.timeslots' => 'Vortragszeiten',	
		'tx_wseevents_sessions.categorie' => 'Kategorie',	
		'tx_wseevents_sessions.number' => 'Vortragsnummer',	
		'tx_wseevents_sessions.teaser' => 'Kurztext',	
		'tx_wseevents_sessions.description' => 'Vortrags Beschreibung',	
		'tx_wseevents_speakers' => 'WSE Sprecher',	
		'tx_wseevents_speakers.name' => 'Name',	
		'tx_wseevents_speakers.email' => 'E-Mail Adresse',	
		'tx_wseevents_categories' => 'WSE Kategorien',	
		'tx_wseevents_categories.name' => 'Name der Kategorie',	
		'tx_wseevents_categories.shortkey' => 'Kurzbezeichnung',	
		'tt_content.list_type_pi1' => 'WSE Veranstaltungen',	
	),
	'fr' => Array (
	),
	'nl' => Array (
		'tx_wseevents_events' => 'WSE Conferentie',	
		'tx_wseevents_events.name' => 'Conferentie nam',	
	),
);
?>